[General]
Font="JetBrainsMono Nerd Font"
ClockEnabled="true"
ClockPosition="center"
CustomBackground="false"
LoginBackground="true"
Background="backgrounds/wallpaper.jpg"
FontSize=12
bgDark="#161616"
bgDefault="#1a1a1a"
textDefault="#e6e6e6"
textHighlight="#ffffff"
textPlaceholder="#555555"
buttonBgNormal="#1a1a1a"
buttonBorderNormal="#e6e6e6"
buttonBgHovered0="#262626"
buttonBgHovered1="#333333"
buttonBorderHovered="#ffffff"
buttonBgPressed="#333333"
buttonBorderPressed="#e6e6e6"
buttonBgFocused0="#262626"
buttonBgFocused1="#333333"
buttonBorderFocused="#ffffff"
lineeditBgNormal="#1a1a1a"
lineeditBorderNormal="#555555"
lineeditBorderHovered="#e6e6e6"
lineeditBorderFocused="#ffffff"
viewitemBgHovered="#262626"
viewitemBorderHovered="#e6e6e6"
viewitemBgPressed="#333333"
viewitemBorderPressed="#ffffff"
opacityPanel="0.95"
opacityDefault="0.90"
