# Standard Steam Gamescope session defaults.
# This is sourced by the Gamescope session scripts.
# Resolution/refresh selections are remembered per display in ~/.config/gamescope/modes.cfg

OUTPUT_CONNECTOR=DP-1
ADAPTIVE_SYNC=1
# SCREEN_WIDTH=2560
# SCREEN_HEIGHT=1440
# INTERNAL_WIDTH=1280
# INTERNAL_HEIGHT=800
