#!/usr/bin/env bash
set -euo pipefail

# Accent theme switcher — multi-color, system-wide
# Usage: accent-theme.sh {waybar|current|toggle|next|list|apply <name>|menu}

THEME_DIR="$HOME/.config/theme"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/hypr"
STATE_FILE="$STATE_DIR/accent-theme"
EWW_DIR="$HOME/.config/eww"
HYPR_CONF="$HOME/.config/hypr/conf"
HYPRLock_CONF="$HOME/.config/hypr/hyprlock.conf"

mkdir -p "$STATE_DIR" "$THEME_DIR"

# ── Palette ──────────────────────────────────────────────────────────────
# name: hex dim soft bg border glow_rgb
get_palette() {
  case "$1" in
    green)  echo "#3fb950 #2ea043 #7ee787 #12261a #1f5132 63,185,80" ;;
    purple) echo "#9b5cff #7d46e8 #b894ff #171022 #3a2463 155,92,255" ;;
    cyan)   echo "#58a6ff #388bfd #79c0ff #0d1d30 #1f3a5f 88,166,255" ;;
    red)    echo "#ff7b72 #da3633 #ffa198 #2a1215 #5c2124 255,123,114" ;;
    amber)  echo "#d29922 #bb8009 #e3b341 #2a2007 #5c3f0e 210,153,34" ;;
    *)      echo "#3fb950 #2ea043 #7ee787 #12261a #1f5132 63,185,80" ;;
  esac
}

ALL_ACCENTS="green purple cyan red amber"

current(){ [[ -f "$STATE_FILE" ]] && cat "$STATE_FILE" || echo green; }

# ── Write CSS (waybar, wofi, swaync) ────────────────────────────────────
write_css() {
  local name=$1 accent dim soft bg border
  read -r accent dim soft bg border _ <<< "$(get_palette "$name")"
  cat > "$THEME_DIR/current-accent.css" << CSS
@define-color accent ${accent};
@define-color accent_dim ${dim};
@define-color accent_soft ${soft};
@define-color accent_bg ${bg};
@define-color accent_border ${border};
CSS
}

# ── Write SCSS (eww) ────────────────────────────────────────────────────
write_scss() {
  local name=$1 accent dim soft bg border glow_rgb
  read -r accent dim soft bg border glow_rgb <<< "$(get_palette "$name")"
  cat > "$EWW_DIR/accent.scss" << SCSS
// Auto-generated by accent-theme.sh — do not edit
\$accent: ${accent};
\$accent-dim: ${dim};
\$accent-soft: ${soft};
\$accent-bg: ${bg};
\$accent-border: ${border};
\$accent-glow: rgba(${glow_rgb}, 0.3);
SCSS
}

# ── Write Hyprland accent config ────────────────────────────────────────
write_hypr_accent() {
  local name=$1 accent
  read -r accent _ <<< "$(get_palette "$name")"
  local hex="${accent#\#}"
  cat > "$HYPR_CONF/accent-colors.conf" << CONF
# Auto-generated by accent-theme.sh
general {
    col.active_border = rgb(${hex})
}
group {
    groupbar {
        col.active = rgb(${hex}) rgb(161b22) 90deg
    }
}
CONF
}

# ── Update hyprlock accent variable ─────────────────────────────────────
write_hyprlock() {
  local name=$1 accent
  read -r accent _ <<< "$(get_palette "$name")"
  local hex="${accent#\#}"
  if [[ -f "$HYPRLock_CONF" ]]; then
    sed -i "s|^\$accent = rgb(.*)$|\$accent = rgb(${hex})|" "$HYPRLock_CONF"
  fi
}

# ── Apply Hyprland live ─────────────────────────────────────────────────
apply_hypr() {
  local name=$1 accent
  read -r accent _ <<< "$(get_palette "$name")"
  local hex="${accent#\#}"
  command -v hyprctl >/dev/null 2>&1 || return 0
  hyprctl keyword general:col.active_border "rgb(${hex})" >/dev/null 2>&1 || true
  hyprctl keyword group:groupbar:col.active "rgb(${hex}) rgb(161b22) 90deg" >/dev/null 2>&1 || true
}

# ── Reload UI ────────────────────────────────────────────────────────────
reload_ui() {
  pkill -USR2 waybar 2>/dev/null || true
  command -v swaync-client >/dev/null 2>&1 && swaync-client --reload-config >/dev/null 2>&1 || true
  # Reload eww if sidebar is open
  command -v eww >/dev/null 2>&1 && eww reload 2>/dev/null || true
}

# ── Notify ───────────────────────────────────────────────────────────────
notify() {
  local name=$1
  command -v notify-send >/dev/null 2>&1 && notify-send -a Theme "Accent: ${name}" || true
}

# ── Waybar JSON output ───────────────────────────────────────────────────
waybar_json() {
  local t short_name class
  t=$(current)
  short_name=$(echo "$t" | cut -c1-3 | tr '[:lower:]' '[:upper:]')
  class="accent-${t}"
  jq -cn --arg text "[ ACC ${short_name} ]" --arg class "$class" --arg tooltip "Click: next accent
Current: ${t}
All: ${ALL_ACCENTS}" '{text: $text, class: $class, tooltip: $tooltip}'
}

# ── Apply theme ──────────────────────────────────────────────────────────
apply() {
  local name="${1:-}"
  # Validate
  local found=0
  for a in $ALL_ACCENTS; do [[ "$a" == "$name" ]] && found=1 && break; done
  [[ "$found" == "1" ]] || { echo "invalid theme: $name (options: $ALL_ACCENTS)" >&2; exit 1; }

  write_css "$name"
  write_scss "$name"
  write_hypr_accent "$name"
  write_hyprlock "$name"
  printf '%s' "$name" > "$STATE_FILE"
  apply_hypr "$name"
  reload_ui
  notify "$name"
}

# ── Cycle to next accent ────────────────────────────────────────────────
cycle() {
  local cur next_flag=0 next=""
  cur=$(current)
  for a in $ALL_ACCENTS; do
    if [[ "$next_flag" == "1" && -z "$next" ]]; then
      next="$a"
      break
    fi
    [[ "$a" == "$cur" ]] && next_flag=1
  done
  # Wrap around
  [[ -z "$next" ]] && next="$(echo "$ALL_ACCENTS" | awk '{print $1}')"
  apply "$next"
}

# ── Wofi menu ────────────────────────────────────────────────────────────
menu() {
  local cur choices chosen
  cur=$(current)
  choices=""
  for a in $ALL_ACCENTS; do
    if [[ "$a" == "$cur" ]]; then
      choices="${choices}  ● ${a} (current)\n"
    else
      choices="${choices}    ${a}\n"
    fi
  done
  chosen=$(echo -e "$choices" | wofi --show dmenu --prompt "Accent" --width 220 --height 240 \
    --cache-file /dev/null --conf /dev/null --style ~/.config/wofi/style.css 2>/dev/null \
    | sed 's/[● ]//g' | awk '{print $1}')
  [[ -n "$chosen" ]] && apply "$chosen"
}

# ── Main ─────────────────────────────────────────────────────────────────
case "${1:-waybar}" in
  waybar|current) waybar_json ;;
  toggle|next) cycle ;;
  list) echo "$ALL_ACCENTS" ;;
  apply) apply "${2:?missing theme name}" ;;
  menu) menu ;;
  *) echo "usage: $0 {waybar|current|toggle|next|list|apply <name>|menu}" >&2; exit 1 ;;
esac
