####################
### APPEARANCE ###
####################

general {
    gaps_in = 4
    gaps_out = 14

    col.active_border = rgb(3fb950)
    col.inactive_border = rgba(2d333bdd)

    border_size = 1
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 0.98

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

group {
    groupbar {
        col.active = rgb(3fb950) rgb(161b22) 90deg
        col.inactive = rgba(161b22dd)
    }
}

animations {
    enabled = true

    bezier = snappy, 0.2, 1.0, 0.3, 1.0
    bezier = quick, 0.15, 0, 0.1, 1

    animation = windows, 1, 3, snappy
    animation = windowsIn, 1, 3, snappy, popin 96%
    animation = windowsOut, 1, 2, quick, popin 96%
    animation = border, 1, 4, snappy
    animation = fade, 1, 3, quick
    animation = workspaces, 1, 3, snappy, fade
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = rgb(0d1117)
    vrr = 1
}
