#################
### AUTOSTART ###
#################

# Core session services
exec-once = waybar & swaync
exec-once = nm-applet --indicator & blueman-applet
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /home/pacey/.config/hypr/xdg-portal-hyprland
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Personal startup apps
exec-once = /usr/bin/1password & sleep 1 && kitty

# Steam gaming mode experiments
#exec-once = gamescope -e -f -w 2560 -h 1440 -r 165 --hdr-enabled -- steam -gamepadui -steamos3
