#################
### AUTOSTART ###
#################

exec-once = waybar & swaync
exec-once = hypridle
exec-once = nm-applet --indicator & blueman-applet
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /home/pacey/.config/hypr/xdg-portal-hyprland
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Personal startup apps
exec-once = /usr/bin/1password & sleep 1 && kitty
