#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 3
    gaps_out = 10

    col.active_border = rgb(7f12ff)
    col.inactive_border = rgba(25252588)

    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 2
    active_opacity = 1.0
    inactive_opacity = 0.97

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

group {
    groupbar {
        col.active = rgb(7f12ff) rgb(1a1a1a) 90deg
        col.inactive = rgba(1a1a1add)
    }
}

animations {
    enabled = true

    bezier = snappy, 0.2, 1.0, 0.3, 1.0
    bezier = quick, 0.15, 0, 0.1, 1

    animation = windows, 1, 3, snappy
    animation = windowsIn, 1, 3, snappy, popin 90%
    animation = windowsOut, 1, 2, quick, popin 90%
    animation = border, 1, 4, snappy
    animation = fade, 1, 3, quick
    animation = workspaces, 1, 3, snappy, fade
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = rgb(0a0a0a)
    vrr = 1
}
