################
### MONITORS ###
################

# Active desktop monitor (HDR-enabled Hyprland path)
monitor = DP-1,2560x1440@90,0x0,auto,bitdepth,10,cm,hdr,sdrbrightness,1.2,sdrsaturation,0.98,vrr,1

# Quick SDR fallback if HDR acts up
#monitor = DP-1,2560x1440@90,0x0,auto,bitdepth,12,vrr,1

# Common desktop alternates
#monitor = DP-1,2560x1440@165,0x0,auto,bitdepth,12,vrr,1
#monitor = DP-1,3840x2160@60,0x0,auto,bitdepth,12,vrr,1
#monitor = DP-2,1920x1080@144,2560x0,auto,bitdepth,12,vrr,1
#monitor = DP-3,1920x1080@144,2560x0,auto,bitdepth,12,vrr,1

# TV presets
#monitor = HDMI-A-1,3840x2160@60,4480x0,auto,bitdepth,10
#monitor = HDMI-A-1,1920x1080@120,4480x0,auto,bitdepth,10

# Mirror presets
#monitor = DP-1,2560x1440@165,0x0,auto,bitdepth,12,vrr,1
#monitor = DP-1,1920x1080@120,0x0,auto,bitdepth,12,vrr,1
#monitor = DP-2,1920x1080@144,auto,auto,bitdepth,12,vrr,1
monitor = HDMI-A-1,3840x2160@60,auto,auto,bitdepth,10,mirror,DP-1
#monitor = HDMI-A-1,1920x1080@120,auto,auto,bitdepth,10,mirror,DP-1
