##############################
### WINDOWS AND WORKSPACES ###
##############################

window = suppressevent maximize, class:.*
window = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

window = opacity 0.0 override 0.0 override, class:^(xwaylandvideobridge)$
window = noanim, class:^(xwaylandvideobridge)$
window = noinitialfocus, class:^(xwaylandvideobridge)$
window = maxsize 1 1, class:^(xwaylandvideobridge)$
window = noblur, class:^(xwaylandvideobridge)$

window = float, class:^(ops-dashboard)$
window = center, class:^(ops-dashboard)$
window = size 1500 920, class:^(ops-dashboard)$

ecosystem:no_update_news = true
